name: flutter_bluetooth_printer_demo
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  flutter_blue_plus: ^1.33.6
  esc_pos_utils:
    git:
      url: https://github.com/twintra/esc_pos_utils.git
  image: ^3.3.0
  provider: ^6.1.2
  permission_handler: ^11.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
